// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO16BgPa5TDF9qbJgVG7AEvTNGZyMyQQo',
    appId: '1:201772686617:web:90c071bdd84b148b43f988',
    messagingSenderId: '201772686617',
    projectId: 'fir-todo-app-b4ac8',
    authDomain: 'fir-todo-app-b4ac8.firebaseapp.com',
    storageBucket: 'fir-todo-app-b4ac8.firebasestorage.app',
    measurementId: 'G-NWN75QMYBG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBBKJYbxMpCOuQTfCHdJ2Nd8ISACoasek',
    appId: '1:201772686617:android:94a151fd0a07287c43f988',
    messagingSenderId: '201772686617',
    projectId: 'fir-todo-app-b4ac8',
    storageBucket: 'fir-todo-app-b4ac8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkm7tPWIqq6C4UqdRBRqKqQ9tpjm8rBUQ',
    appId: '1:201772686617:ios:c5859d9f194b808943f988',
    messagingSenderId: '201772686617',
    projectId: 'fir-todo-app-b4ac8',
    storageBucket: 'fir-todo-app-b4ac8.firebasestorage.app',
    iosBundleId: 'com.example.firebaseTodoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkm7tPWIqq6C4UqdRBRqKqQ9tpjm8rBUQ',
    appId: '1:201772686617:ios:c5859d9f194b808943f988',
    messagingSenderId: '201772686617',
    projectId: 'fir-todo-app-b4ac8',
    storageBucket: 'fir-todo-app-b4ac8.firebasestorage.app',
    iosBundleId: 'com.example.firebaseTodoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDO16BgPa5TDF9qbJgVG7AEvTNGZyMyQQo',
    appId: '1:201772686617:web:46806da93378eabd43f988',
    messagingSenderId: '201772686617',
    projectId: 'fir-todo-app-b4ac8',
    authDomain: 'fir-todo-app-b4ac8.firebaseapp.com',
    storageBucket: 'fir-todo-app-b4ac8.firebasestorage.app',
    measurementId: 'G-NDKNLPNMED',
  );
}
